version: "3.9"

services:

  postgres:
    image: postgres:17-alpine
    container_name: syncra-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: syncra

    ports:
      - "5432:5432"

  redis:
    image: redis:8-alpine
    container_name: syncra-redis

    ports:
      - "6379:6379"