// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getAllSessions = `-- name: GetAllSessions :many
SELECT s.id, s.user_id, s.refresh_token_hash, s.user_agent, s.ip_address, s.expired_at, s.revoked_at, s.created_at
FROM SESSIONS as s
WHERE
    s.user_id = $1
    AND s.deleted_at IS NULL
    AND s.revoked_at IS NULL
`

type GetAllSessionsRow struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	UserAgent        sql.NullString `json:"user_agent"`
	IpAddress        pqtype.Inet    `json:"ip_address"`
	ExpiredAt        time.Time      `json:"expired_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) GetAllSessions(ctx context.Context, userID uuid.UUID) ([]GetAllSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSessionsRow
	for rows.Next() {
		var i GetAllSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiredAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionById = `-- name: GetSessionById :one
SELECT s.id, s.user_id, s.refresh_token_hash, s.user_agent, s.ip_address, s.expired_at, s.revoked_at, s.created_at
FROM SESSIONS as s
WHERE
    s.user_id = $1
    AND s.id = $2
    AND s.deleted_at IS NULL
    AND s.revoked_at IS NULL
`

type GetSessionByIdParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetSessionByIdRow struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	UserAgent        sql.NullString `json:"user_agent"`
	IpAddress        pqtype.Inet    `json:"ip_address"`
	ExpiredAt        time.Time      `json:"expired_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) GetSessionById(ctx context.Context, arg GetSessionByIdParams) (GetSessionByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, arg.UserID, arg.ID)
	var i GetSessionByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiredAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const saveSession = `-- name: SaveSession :exec
INSERT INTO
    sessions (
        id,
        user_id,
        user_agent,
        refresh_token_hash,
        expired_at
    )
VALUES ($1, $2, $3, $4, $5)
`

type SaveSessionParams struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	UserAgent        sql.NullString `json:"user_agent"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	ExpiredAt        time.Time      `json:"expired_at"`
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.ExecContext(ctx, saveSession,
		arg.ID,
		arg.UserID,
		arg.UserAgent,
		arg.RefreshTokenHash,
		arg.ExpiredAt,
	)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE SESSIONS s SET s.revoked_at = now() WHERE s.id = $1
`

func (q *Queries) UpdateSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateSession, id)
	return err
}
