// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type Mutation struct {
}

type Post struct {
	ID       string `json:"id"`
	AuthorID string `json:"authorId"`
	Title    string `json:"title"`
	Body     string `json:"body"`
}

type Query struct {
}
